version: "1"
services:
  # PostgreSQL Database for Auth Service
  - type: psql
    name: auge-auth-db
    region: frankfurt # Or choose a region closer to you/your users
    plan: free # Or your desired plan
    postgresMajorVersion: 15 # Specify PostgreSQL version
    ipAllowList: [] # Allows all IPs, or restrict as needed

  # Auth Service (FastAPI)
  - type: web
    name: auge-auth-service
    env: python
    region: frankfurt # Match DB region if possible
    plan: free # Or your desired plan
    branch: main # Or your default branch
    rootDir: backend/auth_service
    buildFilter:
      paths:
      - "backend/auth_service/**"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/ping" # Endpoint for health checks
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: AUTH_DATABASE_URL
        fromDatabase:
          name: auge-auth-db
          property: connectionString
      - key: AUTH_SECRET_KEY
        generateValue: true # Render can generate a secure secret key
      - key: AUTH_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      # Add any other necessary environment variables for auth_service here
      # Example: If you have specific CORS origins
      # - key: CORS_ORIGINS
      #   value: "https://your-frontend-domain.vercel.app,http://localhost:3000"

# TODO: Add data_collector_service and its database (if separate) later
# - type: psql
#   name: auge-market-data-db
#   ...
# - type: web
#   name: auge-data-collector-service
#   rootDir: backend/data_collector_service
#   ...

